### ISSUE TITLE
M1 Mac (Apple silicon) make issues

### ISSUE THREAD

**Issue by NicholasNelsonwood** [samuelsadok/fibre-cpp#2]
I have been trying to build this app on a M1 mac but haven't had any luck. I have `libusb` install via `homebrew` but when I try to run `make` I get the following error:

`Makefile:25: *** commands commence before first target.  Stop.`

I feel like it might be something simple I am missing but haven't been able to make much progress. I have tried reinstalling `libusb`, moving the folder out of /opt/local to ~/Desktop, and a few other things that I don't exactly remember.

Has anyone had luck using this on an M1 mac? Any specific steps I need to take? Is my issue not at all related to the computer architecture?

P.S.

(If it is at all helpful I am trying to compile from source as that is what the error recommends when I try to install odrivetool):

```
fibre-cpp % python -m pip install --upgrade odrive
Defaulting to user installation because normal site-packages is not writeable
Collecting odrive
  Using cached odrive-0.5.4.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1w/cryb3hyd6656h0_39q7mrzz80000gn/T/pip-install-__vwapou/odrive_b0e6274eb31c413485667cec0191470a/setup.py", line 61, in <module>
          import odrive.version
        File "/private/var/folders/1w/cryb3hyd6656h0_39q7mrzz80000gn/T/pip-install-__vwapou/odrive_b0e6274eb31c413485667cec0191470a/odrive/__init__.py", line 9, in <module>
          import fibre
        File "/private/var/folders/1w/cryb3hyd6656h0_39q7mrzz80000gn/T/pip-install-__vwapou/odrive_b0e6274eb31c413485667cec0191470a/odrive/pyfibre/fibre/__init__.py", line 4, in <module>
          from .libfibre import Domain, ObjectLostError
        File "/private/var/folders/1w/cryb3hyd6656h0_39q7mrzz80000gn/T/pip-install-__vwapou/odrive_b0e6274eb31c413485667cec0191470a/odrive/pyfibre/fibre/libfibre.py", line 53, in <module>
          raise ModuleNotFoundError("libfibre is not supported on your platform ({} {}). {}".format(*system_desc, instructions))
      ModuleNotFoundError: libfibre is not supported on your platform (Darwin arm64). Go to https://github.com/samuelsadok/fibre-cpp for instructions on how to compile libfibre. Once you have compiled it, add it to this folder.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by samuelsadok** [comment]
If you're building libfibre for ODrive I recommend to build it from the ODrive repository because then you know it's the right version (the fibre repo contains some changes that have not yet been merged to ODrive).

Please see https://docs.odriverobotics.com/v/latest/developer-guide.html#modifying-libfibre for more info. You might need to slightly modify a build file or two for your new platform (like Firmware/fibre-cpp/Tupfile.lua).

**Comment by NicholasNelsonwood** [comment]
That makes a lot of sense. Thanks for the response

**Comment by NicholasNelsonwood** [comment]
For anyone finding the post [here](https://discourse.odriverobotics.com/t/odrivetool-install-on-m1-mac-apple-silicon/8798) shows what I ultimately did to get Odrivetool working on an M1 mac:
